# Generated by Django 4.0.5 on 2022-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Profile_picture',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Username',
        ),
        migrations.AddField(
            model_name='contact',
            name='Firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='profilepicture',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
